/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        | {
            href?: string;
            openInNewTab?: boolean;
            noFollow?: boolean;
            _type: "link";
            _key: string;
          }
        | {
            reference?: PostReference | CategoryReference;
            _type: "internalLink";
            _key: string;
          }
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
  | {
      tone?: "info" | "tip" | "warning";
      body: string;
      _type: "callout";
      _key: string;
    }
  | {
      language?:
        | "typescript"
        | "javascript"
        | "tsx"
        | "jsx"
        | "html"
        | "css"
        | "bash"
        | "json"
        | "yaml"
        | "groq"
        | "sql"
        | "python";
      code?: string;
      filename?: string;
      _type: "code";
      _key: string;
    }
>;

export type BlogSettings = {
  _id: string;
  _type: "blogSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  excerpt?: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  body?: BlockContent;
  author: AuthorReference;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  estimatedReadingTime?: number;
  featured?: boolean;
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    noIndex?: boolean;
    canonicalUrl?: string;
  };
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  role?: string;
  picture?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  bio?: string;
  social?: {
    twitter?: string;
    linkedin?: string;
    github?: string;
    website?: string;
  };
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
  color?: "slate" | "indigo" | "emerald" | "amber" | "rose" | "sky";
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | PostReference
  | CategoryReference
  | SanityImageAssetReference
  | BlockContent
  | BlogSettings
  | SanityImageCrop
  | SanityImageHotspot
  | AuthorReference
  | Post
  | Author
  | Slug
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: SETTINGS_QUERY
// Query: *[_type == "blogSettings"][0]{    title,    description,    ogImage {      ...,      asset->{ _id, url, metadata { lqip } }    }  }
export type SETTINGS_QUERY_RESULT = {
  title: string;
  description: string | null;
  ogImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)]  | order(coalesce(publishedAt, _updatedAt) desc) [$start...$end] {      _id,  _type,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  title,  "slug": slug.current,  excerpt,  publishedAt,  _updatedAt,  coverImage {    ...,    asset->{      _id,      url,      metadata { lqip, dimensions }    },    alt  },  estimatedReadingTime,  author->{    _id,    name,    "slug": slug.current,    role,    picture {      ...,      asset->{ _id, url, metadata { lqip } },      alt    }  },  categories[]->{    _id,    title,    "slug": slug.current,    color  },  seo  }
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "post";
  status: "draft" | "published";
  title: string;
  slug: string;
  excerpt: string | null;
  publishedAt: string | null;
  _updatedAt: string;
  coverImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  estimatedReadingTime: number | null;
  author: {
    _id: string;
    name: string;
    slug: string;
    role: string | null;
    picture: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    } | null;
  };
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
    color: "amber" | "emerald" | "indigo" | "rose" | "sky" | "slate" | null;
  }> | null;
  seo: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    noIndex?: boolean;
    canonicalUrl?: string;
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: POSTS_COUNT_QUERY
// Query: count(*[_type == "post" && defined(slug.current)])
export type POSTS_COUNT_QUERY_RESULT = number;

// Source: sanity/lib/queries.ts
// Variable: FEATURED_POST_QUERY
// Query: *[_type == "post" && defined(slug.current) && featured == true]  | order(coalesce(publishedAt, _updatedAt) desc)[0] {      _id,  _type,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  title,  "slug": slug.current,  excerpt,  publishedAt,  _updatedAt,  coverImage {    ...,    asset->{      _id,      url,      metadata { lqip, dimensions }    },    alt  },  estimatedReadingTime,  author->{    _id,    name,    "slug": slug.current,    role,    picture {      ...,      asset->{ _id, url, metadata { lqip } },      alt    }  },  categories[]->{    _id,    title,    "slug": slug.current,    color  },  seo  }
export type FEATURED_POST_QUERY_RESULT = {
  _id: string;
  _type: "post";
  status: "draft" | "published";
  title: string;
  slug: string;
  excerpt: string | null;
  publishedAt: string | null;
  _updatedAt: string;
  coverImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  estimatedReadingTime: number | null;
  author: {
    _id: string;
    name: string;
    slug: string;
    role: string | null;
    picture: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    } | null;
  };
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
    color: "amber" | "emerald" | "indigo" | "rose" | "sky" | "slate" | null;
  }> | null;
  seo: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    noIndex?: boolean;
    canonicalUrl?: string;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)]{ "slug": slug.current }
export type POST_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: SITEMAP_POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)]{    "slug": slug.current,    _updatedAt  }
export type SITEMAP_POSTS_QUERY_RESULT = Array<{
  slug: string;
  _updatedAt: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: POST_BY_SLUG_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{      _id,  _type,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  title,  "slug": slug.current,  excerpt,  publishedAt,  _updatedAt,  coverImage {    ...,    asset->{      _id,      url,      metadata { lqip, dimensions }    },    alt  },  estimatedReadingTime,  author->{    _id,    name,    "slug": slug.current,    role,    picture {      ...,      asset->{ _id, url, metadata { lqip } },      alt    }  },  categories[]->{    _id,    title,    "slug": slug.current,    color  },  seo,    body[]{      ...,      _type == "image" => {        ...,        asset->{ _id, url, metadata { lqip, dimensions } }      },      markDefs[]{        ...,        _type == "internalLink" => {          "slug": @.reference->slug.current,          "type": @.reference->_type        }      }    }  }
export type POST_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "post";
  status: "draft" | "published";
  title: string;
  slug: string;
  excerpt: string | null;
  publishedAt: string | null;
  _updatedAt: string;
  coverImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  estimatedReadingTime: number | null;
  author: {
    _id: string;
    name: string;
    slug: string;
    role: string | null;
    picture: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    } | null;
  };
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
    color: "amber" | "emerald" | "indigo" | "rose" | "sky" | "slate" | null;
  }> | null;
  seo: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    noIndex?: boolean;
    canonicalUrl?: string;
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              reference?: CategoryReference | PostReference;
              _type: "internalLink";
              _key: string;
              slug: string | null;
              type: "category" | "post" | null;
            }
          | {
              href?: string;
              openInNewTab?: boolean;
              noFollow?: boolean;
              _type: "link";
              _key: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        tone?: "info" | "tip" | "warning";
        body: string;
        _type: "callout";
        _key: string;
        markDefs: null;
      }
    | {
        language?:
          | "bash"
          | "css"
          | "groq"
          | "html"
          | "javascript"
          | "json"
          | "jsx"
          | "python"
          | "sql"
          | "tsx"
          | "typescript"
          | "yaml";
        code?: string;
        filename?: string;
        _type: "code";
        _key: string;
        markDefs: null;
      }
    | {
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        caption?: string;
        _type: "image";
        _key: string;
        markDefs: null;
      }
  > | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: MORE_POSTS_QUERY
// Query: *[_type == "post" && slug.current != $slug && defined(slug.current)]  | order(coalesce(publishedAt, _updatedAt) desc) [0...$limit] {      _id,  _type,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  title,  "slug": slug.current,  excerpt,  publishedAt,  _updatedAt,  coverImage {    ...,    asset->{      _id,      url,      metadata { lqip, dimensions }    },    alt  },  estimatedReadingTime,  author->{    _id,    name,    "slug": slug.current,    role,    picture {      ...,      asset->{ _id, url, metadata { lqip } },      alt    }  },  categories[]->{    _id,    title,    "slug": slug.current,    color  },  seo  }
export type MORE_POSTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "post";
  status: "draft" | "published";
  title: string;
  slug: string;
  excerpt: string | null;
  publishedAt: string | null;
  _updatedAt: string;
  coverImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  estimatedReadingTime: number | null;
  author: {
    _id: string;
    name: string;
    slug: string;
    role: string | null;
    picture: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    } | null;
  };
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
    color: "amber" | "emerald" | "indigo" | "rose" | "sky" | "slate" | null;
  }> | null;
  seo: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    noIndex?: boolean;
    canonicalUrl?: string;
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: POST_SEO_BY_SLUG_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{    title,    excerpt,    "slug": slug.current,    publishedAt,    _updatedAt,    author->{ name },    coverImage {      asset->{ url, metadata { dimensions } },      alt    },    seo  }
export type POST_SEO_BY_SLUG_QUERY_RESULT = {
  title: string;
  excerpt: string | null;
  slug: string;
  publishedAt: string | null;
  _updatedAt: string;
  author: {
    name: string;
  };
  coverImage: {
    asset: {
      url: string;
      metadata: {
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string;
  };
  seo: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    noIndex?: boolean;
    canonicalUrl?: string;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category"] | order(title asc) {    _id,    title,    "slug": slug.current,    description,    color  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string | null;
  color: "amber" | "emerald" | "indigo" | "rose" | "sky" | "slate" | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "blogSettings"][0]{\n    title,\n    description,\n    ogImage {\n      ...,\n      asset->{ _id, url, metadata { lqip } }\n    }\n  }\n': SETTINGS_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)]\n  | order(coalesce(publishedAt, _updatedAt) desc) [$start...$end] {\n    \n  _id,\n  _type,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  _updatedAt,\n  coverImage {\n    ...,\n    asset->{\n      _id,\n      url,\n      metadata { lqip, dimensions }\n    },\n    alt\n  },\n  estimatedReadingTime,\n  author->{\n    _id,\n    name,\n    "slug": slug.current,\n    role,\n    picture {\n      ...,\n      asset->{ _id, url, metadata { lqip } },\n      alt\n    }\n  },\n  categories[]->{\n    _id,\n    title,\n    "slug": slug.current,\n    color\n  },\n  seo\n\n  }\n': POSTS_QUERY_RESULT;
    '\n  count(*[_type == "post" && defined(slug.current)])\n': POSTS_COUNT_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current) && featured == true]\n  | order(coalesce(publishedAt, _updatedAt) desc)[0] {\n    \n  _id,\n  _type,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  _updatedAt,\n  coverImage {\n    ...,\n    asset->{\n      _id,\n      url,\n      metadata { lqip, dimensions }\n    },\n    alt\n  },\n  estimatedReadingTime,\n  author->{\n    _id,\n    name,\n    "slug": slug.current,\n    role,\n    picture {\n      ...,\n      asset->{ _id, url, metadata { lqip } },\n      alt\n    }\n  },\n  categories[]->{\n    _id,\n    title,\n    "slug": slug.current,\n    color\n  },\n  seo\n\n  }\n': FEATURED_POST_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)]{ "slug": slug.current }\n': POST_SLUGS_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)]{\n    "slug": slug.current,\n    _updatedAt\n  }\n': SITEMAP_POSTS_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    \n  _id,\n  _type,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  _updatedAt,\n  coverImage {\n    ...,\n    asset->{\n      _id,\n      url,\n      metadata { lqip, dimensions }\n    },\n    alt\n  },\n  estimatedReadingTime,\n  author->{\n    _id,\n    name,\n    "slug": slug.current,\n    role,\n    picture {\n      ...,\n      asset->{ _id, url, metadata { lqip } },\n      alt\n    }\n  },\n  categories[]->{\n    _id,\n    title,\n    "slug": slug.current,\n    color\n  },\n  seo\n,\n    body[]{\n      ...,\n      _type == "image" => {\n        ...,\n        asset->{ _id, url, metadata { lqip, dimensions } }\n      },\n      markDefs[]{\n        ...,\n        _type == "internalLink" => {\n          "slug": @.reference->slug.current,\n          "type": @.reference->_type\n        }\n      }\n    }\n  }\n': POST_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current != $slug && defined(slug.current)]\n  | order(coalesce(publishedAt, _updatedAt) desc) [0...$limit] {\n    \n  _id,\n  _type,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  _updatedAt,\n  coverImage {\n    ...,\n    asset->{\n      _id,\n      url,\n      metadata { lqip, dimensions }\n    },\n    alt\n  },\n  estimatedReadingTime,\n  author->{\n    _id,\n    name,\n    "slug": slug.current,\n    role,\n    picture {\n      ...,\n      asset->{ _id, url, metadata { lqip } },\n      alt\n    }\n  },\n  categories[]->{\n    _id,\n    title,\n    "slug": slug.current,\n    color\n  },\n  seo\n\n  }\n': MORE_POSTS_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    title,\n    excerpt,\n    "slug": slug.current,\n    publishedAt,\n    _updatedAt,\n    author->{ name },\n    coverImage {\n      asset->{ url, metadata { dimensions } },\n      alt\n    },\n    seo\n  }\n': POST_SEO_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "category"] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    color\n  }\n': CATEGORIES_QUERY_RESULT;
  }
}
